version: '3.4'
services:
  kibana:
    labels:
        service: kibana
    image: ${KIBANA_IMAGE}
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: https://elasticsearch03:9200
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      NODE_EXTRA_CA_CERTS: /usr/share/kibana/config/ca_cert.pem
    volumes:
      - storage:/usr/share/kibana/data
    ports:
      - target: 5601
        published: 5601
        protocol: tcp
        mode: ingress
    logging:
      options:
        labels: "service"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
          - node.labels.kibana == true
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.1'
          memory: 1024M
    secrets:
      - source: kibana_key
        target: /usr/share/kibana/config/kibana_key.pem
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: kibana_cert
        target: /usr/share/kibana/config/kibana_cert.pem
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: ca_cert
        target: /usr/share/kibana/config/ca_cert.pem
        uid: '1000'
        gid: '1000'
        mode: 0440
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml
        uid: '1000'
        gid: '1000'
        mode: 0440
networks:
  default:
    external:
      name: services
volumes:
    storage:
secrets:
  kibana_key:
    file: ${ENVIRONMENT_SECRETS_PATH}/kibana/kibana_key.pem
  kibana_cert:
    file: ${ENVIRONMENT_SECRETS_PATH}/kibana/kibana_cert.pem
  ca_cert:
    file: ${ENVIRONMENT_SECRETS_PATH}/kibana/ca_cert.pem
configs:
  kibana_config:
    file: ${SWARM_RESOURCES_PATH}/kibana.yaml
