version: '3.4'
services:
  consul1:
    labels:
        service: consul
    image: ${CONSUL_IMAGE}
    command: "consul agent -server -ui -node=consul1 -datacenter=${CONSUL_DATACENTER} -bootstrap-expect=3 -data-dir=/consul/data -config-dir=/consul/config -client='0.0.0.0' -bind='0.0.0.0' -advertise='{{ GetInterfaceIP \"eth0\" }}' --retry-join=consul2 --retry-join=consul3 -encrypt=${CONSUL_SECRET}"
    environment:
      CONSUL_UI_BETA: "true"
    volumes:
      - storage:/consul/data
    ports:
      - target: 8300
        published: 8300
        protocol: tcp
        mode: host
      - target: 8302
        published: 8302
        protocol: tcp
        mode: host
      - target: 8302
        published: 8302
        protocol: udp
        mode: host
      - target: 8500
        published: 8500
        protocol: tcp
        mode: host
      - target: 8600
        published: 8600
        protocol: tcp
        mode: host
      - target: 8600
        published: 8600
        protocol: udp
        mode: host
    logging:
      options:
        labels: "service"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
          - node.labels.consul == true
          - node.labels.zone == a
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          cpus: '1'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
    secrets:
      - source: ca_cert
        target: /consul/config/ca_cert.pem
        uid: '100'
        gid: '1000'
        mode: 0440
      - source: consul_key
        target: /consul/config/consul_key.pem
        uid: '100'
        gid: '1000'
        mode: 0440
      - source: consul_cert
        target: /consul/config/consul_cert.pem
        uid: '100'
        gid: '1000'
        mode: 0440
    configs:
      - source: consul_config
        target: /consul/config/consul.json
        uid: '100'
        gid: '1000'
        mode: 0440
  consul2:
    labels:
        service: consul
    image: ${CONSUL_IMAGE}
    command: "consul agent -server -ui -node=consul2 -datacenter=${CONSUL_DATACENTER} -bootstrap-expect=3 -data-dir=/consul/data -config-dir=/consul/config -client='0.0.0.0' -bind='0.0.0.0' -advertise='{{ GetInterfaceIP \"eth0\" }}' --retry-join=consul1  --retry-join=consul3 -encrypt=${CONSUL_SECRET}"
    environment:
      CONSUL_UI_BETA: "true"
    volumes:
      - storage:/consul/data
    ports:
      - target: 8300
        published: 8300
        protocol: tcp
        mode: host
      - target: 8302
        published: 8302
        protocol: tcp
        mode: host
      - target: 8302
        published: 8302
        protocol: udp
        mode: host
      - target: 8500
        published: 8500
        protocol: tcp
        mode: host
      - target: 8600
        published: 8600
        protocol: tcp
        mode: host
      - target: 8600
        published: 8600
        protocol: udp
        mode: host
    logging:
      options:
        labels: "service"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
          - node.labels.consul == true
          - node.labels.zone == b
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          cpus: '1'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
    secrets:
      - source: ca_cert
        target: /consul/config/ca_cert.pem
        uid: '100'
        gid: '1000'
        mode: 0440
      - source: consul_key
        target: /consul/config/consul_key.pem
        uid: '100'
        gid: '1000'
        mode: 0440
      - source: consul_cert
        target: /consul/config/consul_cert.pem
        uid: '100'
        gid: '1000'
        mode: 0440
    configs:
      - source: consul_config
        target: /consul/config/consul.json
        uid: '100'
        gid: '1000'
        mode: 0440
  consul3:
    labels:
        service: consul
    image: ${CONSUL_IMAGE}
    command: "consul agent -server -ui -node=consul3 -datacenter=${CONSUL_DATACENTER} -bootstrap-expect=3 -data-dir=/consul/data -config-dir=/consul/config -client='0.0.0.0' -bind='0.0.0.0' -advertise='{{ GetInterfaceIP \"eth0\" }}' --retry-join=consul1 --retry-join=consul2 -encrypt=${CONSUL_SECRET}"
    environment:
      CONSUL_UI_BETA: "true"
    volumes:
      - storage:/consul/data
    ports:
      - target: 8300
        published: 8300
        protocol: tcp
        mode: host
      - target: 8302
        published: 8302
        protocol: tcp
        mode: host
      - target: 8302
        published: 8302
        protocol: udp
        mode: host
      - target: 8500
        published: 8500
        protocol: tcp
        mode: host
      - target: 8600
        published: 8600
        protocol: tcp
        mode: host
      - target: 8600
        published: 8600
        protocol: udp
        mode: host
    logging:
      options:
        labels: "service"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
          - node.labels.consul == true
          - node.labels.zone == c
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          cpus: '1'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
    secrets:
      - source: ca_cert
        target: /consul/config/ca_cert.pem
        uid: '100'
        gid: '1000'
        mode: 0440
      - source: consul_key
        target: /consul/config/consul_key.pem
        uid: '100'
        gid: '1000'
        mode: 0440
      - source: consul_cert
        target: /consul/config/consul_cert.pem
        uid: '100'
        gid: '1000'
        mode: 0440
    configs:
      - source: consul_config
        target: /consul/config/consul.json
        uid: '100'
        gid: '1000'
        mode: 0440
networks:
  default:
    external:
      name: services
volumes:
    storage:
secrets:
  ca_cert:
    file: ${SECRETS_PATH}/ca_cert.pem
  consul_key:
    file: ${SECRETS_PATH}/consul_key.pem
  consul_cert:
    file: ${SECRETS_PATH}/consul_cert.pem
configs:
  consul_config:
    file: consul.json
