version: '3.4'
services:
  kafka1:
    labels:
        service: kafka
    image: ${KAFKA_IMAGE}
    environment:
      BROKER_ID: 1
      ZK_CONNECT: ${DOCKER_HOST_1}:2181
      ADVERTISED_HOST: ${DOCKER_HOST_1}
      ADVERTISED_PORT: 9092
      LISTENERS: SSL://0.0.0.0:9092
      ADVERTISED_LISTENERS: SSL://${DOCKER_HOST_1}:9092
      NUM_PARTITIONS: 1
      DELETE_TOPICS: "true"
      AUTO_CREATE_TOPICS: "false"
      LOG_RETENTION_HOURS: 24
      TRANSACTION_MAX_TIMEOUT_MS: 3600000
      LOG_PATH: "\\/data\\/kafka-logs"
      ZOOKEEPER_SET_ACL: "true"
      SECURITY_INTER_BROKER_PROTOCOL: SSL
      KEYSTORE_LOCATION: /secrets/keystore.jks
      TRUSTSTORE_LOCATION: /secrets/truststore.jks
      KEYSTORE_PASSWORD_LOCATION: /secrets/keystore_password.txt
      TRUSTSTORE_PASSWORD_LOCATION: /secrets/truststore_password.txt
      ZOO_JAAS_CONFIG_LOCATION: /secrets/zookeeper_kafka_jaas.conf
    volumes:
      - kafka_data1:/data
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
    logging:
      options:
        labels: "service"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
          - node.labels.kafka == true
          - node.labels.zone == a
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
      resources:
        limits:
          cpus: '4'
          memory: 1024M
        reservations:
          cpus: '0.1'
          memory: 256M
    secrets:
      - source: keystore1
        target: /secrets/keystore.jks
        uid: '100'
        gid: '1000'
        mode: 0440
      - source: keystore_password1
        target: /secrets/keystore_password.txt
        uid: '100'
        gid: '1000'
        mode: 0440
      - source: truststore1
        target: /secrets/truststore.jks
        uid: '100'
        gid: '1000'
        mode: 0440
      - source: truststore_password1
        target: /secrets/truststore_password.txt
        uid: '100'
        gid: '1000'
        mode: 0440
      - source: jaas_config
        target: /secrets/zookeeper_kafka_jaas.conf
        uid: '100'
        gid: '1000'
        mode: 0440
  kafka2:
    labels:
        service: kafka
    image: ${KAFKA_IMAGE}
    environment:
      BROKER_ID: 2
      ZK_CONNECT: ${DOCKER_HOST_2}:2181
      ADVERTISED_HOST: ${DOCKER_HOST_2}
      ADVERTISED_PORT: 9092
      LISTENERS: SSL://0.0.0.0:9092
      ADVERTISED_LISTENERS: SSL://${DOCKER_HOST_2}:9092
      NUM_PARTITIONS: 1
      DELETE_TOPICS: "true"
      AUTO_CREATE_TOPICS: "false"
      LOG_RETENTION_HOURS: 24
      TRANSACTION_MAX_TIMEOUT_MS: 3600000
      LOG_PATH: "\\/data\\/kafka-logs"
      ZOOKEEPER_SET_ACL: "true"
      SECURITY_INTER_BROKER_PROTOCOL: SSL
      KEYSTORE_LOCATION: /secrets/keystore.jks
      TRUSTSTORE_LOCATION: /secrets/truststore.jks
      KEYSTORE_PASSWORD_LOCATION: /secrets/keystore_password.txt
      TRUSTSTORE_PASSWORD_LOCATION: /secrets/truststore_password.txt
      ZOO_JAAS_CONFIG_LOCATION: /secrets/zookeeper_kafka_jaas.conf
    volumes:
      - kafka_data2:/data
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
    logging:
      options:
        labels: "service"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
          - node.labels.kafka == true
          - node.labels.zone == b
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
      resources:
        limits:
          cpus: '4'
          memory: 1024M
        reservations:
          cpus: '0.1'
          memory: 256M
    secrets:
      - source: keystore2
        target: /secrets/keystore.jks
        uid: '100'
        gid: '1000'
        mode: 0440
      - source: keystore_password2
        target: /secrets/keystore_password.txt
        uid: '100'
        gid: '1000'
        mode: 0440
      - source: truststore2
        target: /secrets/truststore.jks
        uid: '100'
        gid: '1000'
        mode: 0440
      - source: truststore_password2
        target: /secrets/truststore_password.txt
        uid: '100'
        gid: '1000'
        mode: 0440
      - source: jaas_config
        target: /secrets/zookeeper_kafka_jaas.conf
        uid: '100'
        gid: '1000'
        mode: 0440
  kafka3:
    labels:
        service: kafka
    image: ${KAFKA_IMAGE}
    environment:
      BROKER_ID: 3
      ZK_CONNECT: ${DOCKER_HOST_3}:2181
      ADVERTISED_HOST: ${DOCKER_HOST_3}
      ADVERTISED_PORT: 9092
      LISTENERS: SSL://0.0.0.0:9092
      ADVERTISED_LISTENERS: SSL://${DOCKER_HOST_3}:9092
      NUM_PARTITIONS: 1
      DELETE_TOPICS: "true"
      AUTO_CREATE_TOPICS: "false"
      LOG_RETENTION_HOURS: 24
      TRANSACTION_MAX_TIMEOUT_MS: 3600000
      LOG_PATH: "\\/data\\/kafka-logs"
      ZOOKEEPER_SET_ACL: "true"
      SECURITY_INTER_BROKER_PROTOCOL: SSL
      KEYSTORE_LOCATION: /secrets/keystore.jks
      TRUSTSTORE_LOCATION: /secrets/truststore.jks
      KEYSTORE_PASSWORD_LOCATION: /secrets/keystore_password.txt
      TRUSTSTORE_PASSWORD_LOCATION: /secrets/truststore_password.txt
      ZOO_JAAS_CONFIG_LOCATION: /secrets/zookeeper_kafka_jaas.conf
    volumes:
      - kafka_data3:/data
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
    logging:
      options:
        labels: "service"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
          - node.labels.kafka == true
          - node.labels.zone == c
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
      resources:
        limits:
          cpus: '4'
          memory: 1024M
        reservations:
          cpus: '0.1'
          memory: 256M
    secrets:
      - source: keystore3
        target: /secrets/keystore.jks
        uid: '100'
        gid: '1000'
        mode: 0440
      - source: keystore_password3
        target: /secrets/keystore_password.txt
        uid: '100'
        gid: '1000'
        mode: 0440
      - source: truststore3
        target: /secrets/truststore.jks
        uid: '100'
        gid: '1000'
        mode: 0440
      - source: truststore_password3
        target: /secrets/truststore_password.txt
        uid: '100'
        gid: '1000'
        mode: 0440
      - source: jaas_config
        target: /secrets/zookeeper_kafka_jaas.conf
        uid: '100'
        gid: '1000'
        mode: 0440
networks:
  default:
    external:
      name: services
volumes:
    kafka_data1:
    kafka_data2:
    kafka_data3:
secrets:
  keystore1:
    file: ${SECRETS_PATH}/kafka1-server-keystore.jks
  keystore_password1:
    file: secrets/password_keystore.txt
  keystore2:
    file: ${SECRETS_PATH}/kafka2-server-keystore.jks
  keystore_password2:
    file: secrets/password_keystore.txt
  keystore3:
    file: ${SECRETS_PATH}/kafka3-server-keystore.jks
  keystore_password3:
    file: secrets/password_keystore.txt
  truststore1:
    file: ${SECRETS_PATH}/kafka1-server-truststore.jks
  truststore_password1:
    file: secrets/password_truststore.txt
  truststore2:
    file: ${SECRETS_PATH}/kafka2-server-truststore.jks
  truststore_password2:
    file: secrets/password_truststore.txt
  truststore3:
    file: ${SECRETS_PATH}/kafka3-server-truststore.jks
  truststore_password3:
    file: secrets/password_truststore.txt
  jaas_config:
    file: secrets/zookeeper_kafka_jaas.conf
