version: '3.4'
services:
  grafana:
    labels:
        service: grafana
    image: ${GRAFANA_IMAGE}
    volumes:
      - storage:/var/lib/grafana
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    logging:
      options:
        labels: "service"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
          - node.labels.grafana == true
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          cpus: '1'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
networks:
  default:
    external:
      name: services
volumes:
    storage:
