version: '3.4'
services:
  elasticsearch1:
    labels:
        service: elasticsearch
    image: ${ELASTICSEARCH_IMAGE}
    environment:
      ES_JAVA_OPTS: "-Xms2G -Xmx2G -Dnetworkaddress.cache.ttl=1"
      network.publish_host: elasticsearch1
      discovery.zen.ping.unicast.hosts: "elasticsearch1,elasticsearch2,elasticsearch3"
      discovery.zen.minimum_master_nodes: 3
    volumes:
      - storage:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        mode: host
      - target: 9300
        published: 9300
        protocol: tcp
        mode: host
    logging:
      options:
        labels: "service"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
          - node.labels.elasticsearch == true
          - node.labels.zone == a
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          cpus: '1'
          memory: 2800M
        reservations:
          cpus: '0.1'
          memory: 2800M
    secrets:
      - source: elasticsearch_key
        target: /usr/share/elasticsearch/config/elasticsearch_key.pem
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: elasticsearch_cert
        target: /usr/share/elasticsearch/config/elasticsearch_cert.pem
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: ca_cert
        target: /usr/share/elasticsearch/config/ca_cert.pem
        uid: '1000'
        gid: '1000'
        mode: 0440
    configs:
      - source: elasticsearch_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        uid: '1000'
        gid: '1000'
        mode: 0440
  elasticsearch2:
    labels:
        service: elasticsearch
    image: ${ELASTICSEARCH_IMAGE}
    environment:
      ES_JAVA_OPTS: "-Xms2G -Xmx2G -Dnetworkaddress.cache.ttl=1"
      network.publish_host: elasticsearch2
      discovery.zen.ping.unicast.hosts: "elasticsearch1,elasticsearch2,elasticsearch3"
      discovery.zen.minimum_master_nodes: 3
    volumes:
      - storage:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        mode: host
      - target: 9300
        published: 9300
        protocol: tcp
        mode: host
    logging:
      options:
        labels: "service"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
          - node.labels.elasticsearch == true
          - node.labels.zone == b
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          cpus: '1'
          memory: 2800M
        reservations:
          cpus: '0.1'
          memory: 2800M
    secrets:
      - source: elasticsearch_key
        target: /usr/share/elasticsearch/config/elasticsearch_key.pem
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: elasticsearch_cert
        target: /usr/share/elasticsearch/config/elasticsearch_cert.pem
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: ca_cert
        target: /usr/share/elasticsearch/config/ca_cert.pem
        uid: '1000'
        gid: '1000'
        mode: 0440
    configs:
      - source: elasticsearch_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        uid: '1000'
        gid: '1000'
        mode: 0440
  elasticsearch3:
    labels:
        service: elasticsearch
    image: ${ELASTICSEARCH_IMAGE}
    environment:
      ES_JAVA_OPTS: "-Xms2G -Xmx2G -Dnetworkaddress.cache.ttl=1"
      network.publish_host: elasticsearch3
      discovery.zen.ping.unicast.hosts: "elasticsearch1,elasticsearch2,elasticsearch3"
      discovery.zen.minimum_master_nodes: 3
    volumes:
      - storage:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        mode: host
      - target: 9300
        published: 9300
        protocol: tcp
        mode: host
    logging:
      options:
        labels: "service"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
          - node.labels.elasticsearch == true
          - node.labels.zone == c
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          cpus: '1'
          memory: 2800M
        reservations:
          cpus: '0.1'
          memory: 2800M
    secrets:
      - source: elasticsearch_key
        target: /usr/share/elasticsearch/config/elasticsearch_key.pem
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: elasticsearch_cert
        target: /usr/share/elasticsearch/config/elasticsearch_cert.pem
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: ca_cert
        target: /usr/share/elasticsearch/config/ca_cert.pem
        uid: '1000'
        gid: '1000'
        mode: 0440
    configs:
      - source: elasticsearch_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        uid: '1000'
        gid: '1000'
        mode: 0440
networks:
  default:
    external:
      name: services
volumes:
    storage:
secrets:
  elasticsearch_key:
    file: ${ENVIRONMENT_SECRETS_PATH}/elasticsearch/elasticsearch_key.pem
  elasticsearch_cert:
    file: ${ENVIRONMENT_SECRETS_PATH}/elasticsearch/elasticsearch_cert.pem
  ca_cert:
    file: ${ENVIRONMENT_SECRETS_PATH}/elasticsearch/ca_cert.pem
configs:
  elasticsearch_config:
    file: ${SWARM_RESOURCES_PATH}/elasticsearch.yaml
