version: '3.4'
services:
  graphite:
    labels:
        service: graphite
    image: ${GRAPHITE_IMAGE}
    volumes:
      - storage:/opt/graphite/storage
    ports:
      - target: 80
        published: 2080
        protocol: tcp
        mode: ingress
      - target: 2003
        published: 2003
        protocol: tcp
        mode: ingress
    logging:
      options:
        labels: "service"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
          - node.labels.graphite == true
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          cpus: '1'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 256M
networks:
  default:
    external:
      name: services
volumes:
    storage:
