version: '3.4'
services:
  consul1:
    labels:
        service: consulagent
    image: consul:latest
    command: 'consul agent -datacenter=${CONSUL_DATACENTER} -data-dir=/consul/data -config-dir=/consul/config -client="0.0.0.0" -bind="0.0.0.0" --retry-join="${DOCKER_HOST_1}" -advertise="${DOCKER_HOST_1}" --retry-join="${DOCKER_HOST_2}" --retry-join="${DOCKER_HOST_3}" -encrypt=${CONSUL_SECRET}'
    ports:
      - target: 8300
        published: 8300
        protocol: tcp
        mode: host
      - target: 8301
        published: 8301
        protocol: tcp
        mode: host
      - target: 8301
        published: 8301
        protocol: udp
        mode: host
      - target: 8302
        published: 8302
        protocol: tcp
        mode: host
      - target: 8302
        published: 8302
        protocol: udp
        mode: host
    logging:
      options:
        labels: "service"
    # Use DNS Round Robin instead VIP for discovery. This ensures we get all running consul server instances when querying consul.server
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
          - node.labels.consulagent == true
          - node.labels.zone == a
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          cpus: '1'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
    secrets:
      - source: ca_cert
        target: /consul/config/ca_cert.pem
        uid: '100'
        gid: '1000'
        mode: 0440
    configs:
      - source: consul1_config
        target: /consul/config/consul.json
        uid: '100'
        gid: '1000'
        mode: 0440
  consul2:
    labels:
        service: consulagent
    image: consul:latest
    command: 'consul agent -datacenter=${CONSUL_DATACENTER} -data-dir=/consul/data -config-dir=/consul/config -client="0.0.0.0" -bind="0.0.0.0" --retry-join="${DOCKER_HOST_1}" -advertise="${DOCKER_HOST_2}" --retry-join="${DOCKER_HOST_2}" --retry-join="${DOCKER_HOST_3}" -encrypt=${CONSUL_SECRET}'
    ports:
      - target: 8300
        published: 8300
        protocol: tcp
        mode: host
      - target: 8301
        published: 8301
        protocol: tcp
        mode: host
      - target: 8301
        published: 8301
        protocol: udp
        mode: host
      - target: 8302
        published: 8302
        protocol: tcp
        mode: host
      - target: 8302
        published: 8302
        protocol: udp
        mode: host
    logging:
      options:
        labels: "service"
    # Use DNS Round Robin instead VIP for discovery. This ensures we get all running consul server instances when querying consul.server
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
          - node.labels.consulagent == true
          - node.labels.zone == b
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          cpus: '1'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
    secrets:
      - source: ca_cert
        target: /consul/config/ca_cert.pem
        uid: '100'
        gid: '1000'
        mode: 0440
    configs:
      - source: consul2_config
        target: /consul/config/consul.json
        uid: '100'
        gid: '1000'
        mode: 0440
  consul3:
    labels:
        service: consulagent
    image: consul:latest
    command: 'consul agent -datacenter=${CONSUL_DATACENTER} -data-dir=/consul/data -config-dir=/consul/config -client="0.0.0.0" -bind="0.0.0.0" --retry-join="${DOCKER_HOST_1}" -advertise="${DOCKER_HOST_3}" --retry-join="${DOCKER_HOST_2}" --retry-join="${DOCKER_HOST_3}" -encrypt=${CONSUL_SECRET}'
    ports:
      - target: 8300
        published: 8300
        protocol: tcp
        mode: host
      - target: 8301
        published: 8301
        protocol: tcp
        mode: host
      - target: 8301
        published: 8301
        protocol: udp
        mode: host
      - target: 8302
        published: 8302
        protocol: tcp
        mode: host
      - target: 8302
        published: 8302
        protocol: udp
        mode: host
    logging:
      options:
        labels: "service"
    # Use DNS Round Robin instead VIP for discovery. This ensures we get all running consul server instances when querying consul.server
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
          - node.labels.consulagent == true
          - node.labels.zone == c
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          cpus: '1'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
    secrets:
      - source: ca_cert
        target: /consul/config/ca_cert.pem
        uid: '100'
        gid: '1000'
        mode: 0440
    configs:
      - source: consul3_config
        target: /consul/config/consul.json
        uid: '100'
        gid: '1000'
        mode: 0440
networks:
  default:
    external:
      name: services
secrets:
  ca_cert:
    file: ${SECRETS_PATH}/ca_cert.pem
configs:
  consul1_config:
    file: consul1.json
  consul2_config:
    file: consul2.json
  consul3_config:
    file: consul3.json
