version: '3.4'
services:
  jenkins:
    labels:
        service: jenkins
    image: jenkins/jenkins:lts
    command:
       - --httpPort=-1
       - --httpsPort=8443
       - --httpsKeyStore=/var/jenkins/keystore.jks
       - --httpsKeyStorePassword=secret
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
    volumes:
      - storage:/var/jenkins_home
    ports:
      - target: 8443
        published: 8443
        protocol: tcp
        mode: host
    logging:
      options:
        labels: "service"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
          - node.labels.jenkins == true
          - node.labels.zone == a
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M
    secrets:
      - source: jenkins_keystore
        target: /var/jenkins/keystore.jks
        uid: '1000'
        gid: '1000'
        mode: 0440
networks:
  default:
    external:
      name: services
volumes:
    storage:
secrets:
  jenkins_keystore:
    file: ${ENVIRONMENT_SECRETS_PATH}/jenkins/keystore.jks
