version: '3.4'
services:
  nginx:
    labels:
        service: nginx
    image: ${NGINX_IMAGE}
    volumes:
      - storage:/data
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
      - target: 443
        published: 443
        protocol: tcp
        mode: ingress
    logging:
      options:
        labels: "service"
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == worker
          - node.labels.nginx == true
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          cpus: '1'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128m
networks:
  default:
    external:
      name: services
volumes:
    storage:
