version: '3.4'
services:
  elasticsearch1:
    labels:
        service: elasticsearch
    image: ${ELASTICSEARCH_IMAGE}
    environment:
      ES_JAVA_OPTS: "-Xms1G -Xmx1G -Dnetworkaddress.cache.ttl=1"
      network.publish_host: ${DOCKER_HOST_1}
    volumes:
      - elasticsearch_data1:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        mode: host
      - target: 9300
        published: 9300
        protocol: tcp
        mode: host
    logging:
      driver: gelf
      options:
        gelf-address: "udp://${DOCKER_HOST_1}:12201"
        labels: "service"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
          - node.labels.elasticsearch == true
          - node.labels.zone == a
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
      resources:
        limits:
          cpus: '2'
          memory: 1.1G
        reservations:
          cpus: '0.1'
          memory: 1.1G
    secrets:
      - source: elasticsearch_key
        target: /usr/share/elasticsearch/config/elasticsearch_key.pem
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: elasticsearch_cert
        target: /usr/share/elasticsearch/config/elasticsearch_cert.pem
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: ca_cert
        target: /usr/share/elasticsearch/config/ca_cert.pem
        uid: '1000'
        gid: '1000'
        mode: 0440
    configs:
      - source: elasticsearch_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        uid: '1000'
        gid: '1000'
        mode: 0440
  elasticsearch2:
    labels:
        service: elasticsearch
    image: ${ELASTICSEARCH_IMAGE}
    environment:
      ES_JAVA_OPTS: "-Xms1G -Xmx1G -Dnetworkaddress.cache.ttl=1"
      network.publish_host: ${DOCKER_HOST_2}
    volumes:
      - elasticsearch_data2:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        mode: host
      - target: 9300
        published: 9300
        protocol: tcp
        mode: host
    logging:
      driver: gelf
      options:
        gelf-address: "udp://${DOCKER_HOST_2}:12201"
        labels: "service"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
          - node.labels.elasticsearch == true
          - node.labels.zone == b
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
      resources:
        limits:
          cpus: '2'
          memory: 1.1G
        reservations:
          cpus: '0.1'
          memory: 1.1G
    secrets:
      - source: elasticsearch_key
        target: /usr/share/elasticsearch/config/elasticsearch_key.pem
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: elasticsearch_cert
        target: /usr/share/elasticsearch/config/elasticsearch_cert.pem
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: ca_cert
        target: /usr/share/elasticsearch/config/ca_cert.pem
        uid: '1000'
        gid: '1000'
        mode: 0440
    configs:
      - source: elasticsearch_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        uid: '1000'
        gid: '1000'
        mode: 0440
  elasticsearch3:
    labels:
        service: elasticsearch
    image: ${ELASTICSEARCH_IMAGE}
    environment:
      ES_JAVA_OPTS: "-Xms1G -Xmx1G -Dnetworkaddress.cache.ttl=1"
      network.publish_host: ${DOCKER_HOST_3}
    volumes:
      - elasticsearch_data3:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        mode: host
      - target: 9300
        published: 9300
        protocol: tcp
        mode: host
    logging:
      driver: gelf
      options:
        gelf-address: "udp://${DOCKER_HOST_3}:12201"
        labels: "service"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
          - node.labels.elasticsearch == true
          - node.labels.zone == c
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
      resources:
        limits:
          cpus: '2'
          memory: 1.1G
        reservations:
          cpus: '0.1'
          memory: 1.1G
    secrets:
      - source: elasticsearch_key
        target: /usr/share/elasticsearch/config/elasticsearch_key.pem
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: elasticsearch_cert
        target: /usr/share/elasticsearch/config/elasticsearch_cert.pem
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: ca_cert
        target: /usr/share/elasticsearch/config/ca_cert.pem
        uid: '1000'
        gid: '1000'
        mode: 0440
    configs:
      - source: elasticsearch_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        uid: '1000'
        gid: '1000'
        mode: 0440
networks:
  default:
    external:
      name: services
volumes:
    elasticsearch_data1:
    elasticsearch_data2:
    elasticsearch_data3:
secrets:
  elasticsearch_key:
    file: ${SECRETS_PATH}/elasticsearch_key.pem
  elasticsearch_cert:
    file: ${SECRETS_PATH}/elasticsearch_cert.pem
  ca_cert:
    file: ${SECRETS_PATH}/ca_cert.pem
configs:
  elasticsearch_config:
    file: elasticsearch.yaml
