version: '3.4'
services:
  sonarqube:
    labels:
        service: sonarqube
    image: sonarqube:7.1
    environment:
      SONARQUBE_JDBC_USERNAME: sonarqube
      SONARQUBE_JDBC_PASSWORD: password
      SONARQUBE_JDBC_URL: jdbc:mysql://mysql:3306/sonar?useUnicode=true&characterEncoding=utf8&useSSL=false
    volumes:
      - storage:/var/lib/sonarqube
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: host
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
    logging:
      options:
        labels: "service"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
          - node.labels.sonarqube == true
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          cpus: '1'
          memory: 600M
        reservations:
          cpus: '0.1'
          memory: 256M
networks:
  default:
    external:
      name: services
volumes:
    storage:
