version: '3.4'
services:
  elasticsearch:
    labels:
        service: elasticsearch
    image: ${ELASTICSEARCH_IMAGE}
    environment:
      ES_JAVA_OPTS: "-Xms740M -Xmx740M -Dnetworkaddress.cache.ttl=1"
      network.publish_host: elasticsearch
      discovery.zen.ping.unicast.hosts: "elasticsearch1,elasticsearch2,elasticsearch3"
      discovery.zen.minimum_master_nodes: 3
      node.master: "false"
      node.ingest: "false"
      node.data: "false"
      node.ml: "false"
    volumes:
      - storage:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        mode: host
      - target: 9300
        published: 9300
        protocol: tcp
        mode: host
    logging:
      options:
        labels: "service"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
          - node.labels.kibana == true
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          cpus: '1'
          memory: 1200M
        reservations:
          cpus: '0.1'
          memory: 1200M
    secrets:
      - source: elasticsearch_key
        target: /usr/share/elasticsearch/config/elasticsearch_key.pem
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: elasticsearch_cert
        target: /usr/share/elasticsearch/config/elasticsearch_cert.pem
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: ca_cert
        target: /usr/share/elasticsearch/config/ca_cert.pem
        uid: '1000'
        gid: '1000'
        mode: 0440
    configs:
      - source: elasticsearch_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        uid: '1000'
        gid: '1000'
        mode: 0440
  kibana:
    labels:
        service: kibana
    image: ${KIBANA_IMAGE}
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: https://elasticsearch:9200
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      NODE_EXTRA_CA_CERTS: /usr/share/kibana/config/ca_cert.pem
    volumes:
      - storage:/usr/share/kibana/data
    ports:
      - target: 5601
        published: 5601
        protocol: tcp
        mode: ingress
    logging:
      options:
        labels: "service"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
          - node.labels.kibana == true
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.1'
          memory: 1024M
    secrets:
      - source: kibana_key
        target: /usr/share/kibana/config/kibana_key.pem
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: kibana_cert
        target: /usr/share/kibana/config/kibana_cert.pem
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: ca_cert
        target: /usr/share/kibana/config/ca_cert.pem
        uid: '1000'
        gid: '1000'
        mode: 0440
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml
        uid: '1000'
        gid: '1000'
        mode: 0440
networks:
  default:
    external:
      name: services
volumes:
    storage:
secrets:
  kibana_key:
    file: ${ENVIRONMENT_SECRETS_PATH}/kibana/kibana_key.pem
  kibana_cert:
    file: ${ENVIRONMENT_SECRETS_PATH}/kibana/kibana_cert.pem
  ca_cert:
    file: ${ENVIRONMENT_SECRETS_PATH}/kibana/ca_cert.pem
  elasticsearch_key:
    file: ${ENVIRONMENT_SECRETS_PATH}/elasticsearch/elasticsearch_key.pem
  elasticsearch_cert:
    file: ${ENVIRONMENT_SECRETS_PATH}/elasticsearch/elasticsearch_cert.pem
  ca_cert:
    file: ${ENVIRONMENT_SECRETS_PATH}/elasticsearch/ca_cert.pem
configs:
  elasticsearch_config:
    file: ${SWARM_RESOURCES_PATH}/elasticsearch.yaml
  kibana_config:
    file: ${SWARM_RESOURCES_PATH}/kibana.yaml
